Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,7 +23,15 @@ jobs:
       run: |
           pip install -r requirements.txt
           pip install jupyter
-        
+
+    - name: Verify models
+      run: |
+       if [ ! -d "models" ]; then
+          echo "Error: models directory not found."
+          exit 1
+       fi
+       ls models/*.pkl || { echo "Error: No .pkl files found in models/"; exit 1; }
+         
     # Step : Run notebook to train models
     - name: Train models from notebook
       run: |
